// <auto-generated />
using System;
using Inventarios.Server.AspNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventarios.Server.AspNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240515161656_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionPal.RazorPages.Models.ProductionGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Final_Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModificationComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("Storage_HistoryId")
                        .HasColumnType("int");

                    b.Property<string>("userIdCreation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userIdModification")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Storage_HistoryId");

                    b.ToTable("productions");
                });

            modelBuilder.Entity("SolutionPal.RazorPages.Models.Storage_History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Production_Id")
                        .HasColumnType("int");

                    b.Property<string>("Storage_Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage_Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Storage_CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Storage_ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Storage_ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Storage_Quantity_Actual")
                        .HasColumnType("float");

                    b.Property<double>("Storage_Quantity_Final")
                        .HasColumnType("float");

                    b.Property<double>("Storage_Quantity_Operation")
                        .HasColumnType("float");

                    b.Property<string>("Storage_userIdCreation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage_userIdModification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("storage_historys");
                });

            modelBuilder.Entity("SolutionPal.RazorPages.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("Storage_HistoryId")
                        .HasColumnType("int");

                    b.Property<string>("userIdCreation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userIdModification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Storage_HistoryId");

                    b.ToTable("stores");
                });

            modelBuilder.Entity("SolutionPal.RazorPages.Models.ProductionGeneral", b =>
                {
                    b.HasOne("SolutionPal.RazorPages.Models.Storage_History", null)
                        .WithMany("productions")
                        .HasForeignKey("Storage_HistoryId");
                });

            modelBuilder.Entity("SolutionPal.RazorPages.Models.Store", b =>
                {
                    b.HasOne("SolutionPal.RazorPages.Models.Storage_History", null)
                        .WithMany("storages")
                        .HasForeignKey("Storage_HistoryId");
                });

            modelBuilder.Entity("SolutionPal.RazorPages.Models.Storage_History", b =>
                {
                    b.Navigation("productions");

                    b.Navigation("storages");
                });
#pragma warning restore 612, 618
        }
    }
}
